### ISSUE TITLE
DayZ 1.19 Can't compile!

### ISSUE THREAD

**Issue by BigRocha** [InclementDab/DayZ-Dabs-Framework#20]
![Screenshot](https://user-images.githubusercontent.com/29151532/218960654-b145784a-5d5f-4f33-a717-3b7493db4c1f.png)

**Comment by jimmyleith** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/12536650/218984325-f9e11118-b285-4e4d-8154-e426afab04f2.png)

**Comment by BigRocha** [comment]
It must have been due to the DayZ update that took place today, I hadn't seen it until now, the stable version went to 1.20, the mod works in the experimental version, so I'm going to update my client and server to see if the problem is solved, please apologies if I opened this issue due to an update I didn't make

**Comment by salutesh** [comment]
Just update game/server to 1.20 and update DF and you should be good.

**Comment by BigRocha** [comment]
Thank you very much, I came back here to say that by updating the client and server to 1.20 everything was solved, but you already commented first ;)
