### ISSUE TITLE
Community appeal.

### ISSUE THREAD

**Issue by AncRad** [InclementDab/DayZ-Dabs-Framework#26]
Stop endlessly updating the mod on the Steam Workshop. Because of this, many servers are constantly rebooted, and the game becomes impossible for a while while you update the modification. Please try releasing one pending Dabs Framework modification update on the Steam Workshop.

**Comment by TheDevilsKnock** [comment]
> Stop endlessly updating the modification in Steam Workshop. Because of this, many servers are constantly being rebooted and the game becomes impossible for the period while you update the modification. Please try to release one delayed update of the Dabs Framework modification in Steam Workshop.

Github Issues is for code revisions. 
Please, write where the faulty code is. 
If you find a fix, feel free to issue a Pull Request

**Comment by AncRad** [comment]
I simply do not have the opportunity to quickly contact those people who are engaged in modding updates in the Steam Workshop, so I am posting this here.

**Comment by TheDevilsKnock** [comment]
> I simply do not have the opportunity to quickly contact those people who are engaged in modding updates in the Steam Workshop, so I am posting this here.

For any other issue, please refer to our [Discord](https://discord.gg/mTHWvZxBTt)

**Comment by AncRad** [comment]
> > I simply do not have the opportunity to quickly contact those people who are engaged in modding updates in the Steam Workshop, so I am posting this here.
> 
> For any other issue, please refer to our [Discord](https://discord.gg/mTHWvZxBTt)

OK, thank you. I'm closing this issue. You can remove it to avoid cluttering repository.
